[project]
name = "home-finder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "ipykernel>=7.1.0",
    "pandas>=2.3.3",
    "streamlit>=1.51.0",
]
